server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      forwarded-headers-strategy: framework
      routes:
        - id: auth
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

logging:
  level:
    org.springframework.cloud.gateway: DEBUG